Update nextjs.yml
debug echo added

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -67,6 +67,10 @@ jobs:
       - name: Build with Next.js
         run: ${{ steps.detect-package-manager.outputs.runner }} next build
         working-directory: ./client
+      - name: Verify Build Output
+        run: ls -R ./dist || echo "dist folder not found!"
+      - name: Check current path
+        run: echo pwd
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with: 
